/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misiontic.reto5.ViewGIU;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import misiontic.reto5.controller.Controller;
import misiontic.reto5.modelo.vo.ComprasVo;
import misiontic.reto5.modelo.vo.LideresVo;
import misiontic.reto5.modelo.vo.ProyectoVo;

/**
 *
 * @author BMO
 */
public class ViewGIU extends javax.swing.JFrame {

    Controller controller;
    //Modelo para tabla
    DefaultTableModel model;

    /**
     * Creates new form ViewGIU
     */
    public ViewGIU() {
        initComponents();
        //aquí se debe inacilizar los arrays de controller o dao
        controller = new Controller();
        model = new DefaultTableModel();
        
        
    }
    

    //Método primera consulta.
    public void showDataLideres() {
        try {
            //se formatea el modelo
            model.setNumRows(controller.listarLideres().size());
            model.addColumn("Lider");
            model.addColumn("Ciudad de Resudencia");

            //se crea la lista de objetos con los valores con el metodo del controller.
            List<LideresVo> lideres = controller.listarLideres();
            //Coloca los valores de la lista en cada columba
            for (int i = 0; i < lideres.size(); i++) {
                model.setValueAt(lideres.get(i).getLider(), i, 0);
                model.setValueAt(lideres.get(i).getCiudadResidencia(), i, 1);

            }
            //se aplica el modelo
            tblResult.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en mostrar datos lideres:" + e.getMessage());
        }

    }

    //Método para setear la tabla para la consulta de proyectos.
    public void showDataProyectos() {
        try {
            model.setNumRows(controller.listarProyecto().size());
            model.addColumn("ID Proyecto");
            model.addColumn("Constructora");
            model.addColumn("Número de habitaciones");
            model.addColumn("Ciudad");
            model.addColumn("Clasificación");

            List<ProyectoVo> proyectos = controller.listarProyecto();

            for (int i = 0; i < proyectos.size(); i++) {
                model.setValueAt(proyectos.get(i).getIdProyecto(), i, 0);
                model.setValueAt(proyectos.get(i).getConstructora(), i, 1);
                model.setValueAt(proyectos.get(i).getNumeroHabitaciones(), i, 2);
                model.setValueAt(proyectos.get(i).getCiudad(), i, 3);
                model.setValueAt(proyectos.get(i).getClasificación(), i, 4);

            }

            tblResult.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en mostrar datos proyecto:" + e.getMessage());
        }

    }

    //método tercer consulta.
    public void showDataCompras() {
        try {
            model.setNumRows(controller.listarCompras().size());
            model.addColumn("ID Compra");
            model.addColumn("Constructora");
            model.addColumn("Banco Vinculado");

            List<ComprasVo> compras = controller.listarCompras();

            for (int i = 0; i < compras.size(); i++) {
                model.setValueAt(compras.get(i).getIdCompra(), i, 0);
                model.setValueAt(compras.get(i).getConstructora(), i, 1);
                model.setValueAt(compras.get(i).getBancoVinculado(), i, 2);

            }

            tblResult.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en mostrar datos proyecto:" + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFirstQuery = new javax.swing.JButton();
        btnSecondQuery = new javax.swing.JButton();
        btnTrirthQuery = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFirstQuery.setText("Primer Consulta");
        btnFirstQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstQueryActionPerformed(evt);
            }
        });

        btnSecondQuery.setText("Segunda Consulta");
        btnSecondQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecondQueryActionPerformed(evt);
            }
        });

        btnTrirthQuery.setText("Tercera Consulta");
        btnTrirthQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrirthQueryActionPerformed(evt);
            }
        });

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnFirstQuery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnSecondQuery)
                .addGap(48, 48, 48)
                .addComponent(btnTrirthQuery)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirstQuery)
                    .addComponent(btnSecondQuery)
                    .addComponent(btnTrirthQuery))
                .addGap(1, 1, 1)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSecondQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecondQueryActionPerformed
        // TODO add your handling code here:
        //el objeto contiene los reportes que son entregados por el controller. 

        try {
            showDataProyectos();

        } catch (Exception e) {
            System.out.println("Error view proyectos: " + e.getMessage());
        }

    }//GEN-LAST:event_btnSecondQueryActionPerformed

    private void btnFirstQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstQueryActionPerformed
        // TODO add your handling code here:
        try {
            model.getDataVector().removeAllElements();
            /*if(model.getColumnCount() > 0){
            } else {
                model.setColumnCount(0);
                model.setRowCount(0);
                tblResult.setModel(model);
            }*/
            showDataLideres();

        } catch (Exception e) {
            System.out.println("Error view líderes: " + e.getMessage());
        }
    }//GEN-LAST:event_btnFirstQueryActionPerformed

    private void btnTrirthQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrirthQueryActionPerformed
        // TODO add your handling code here:
        try {
            showDataCompras();

        } catch (Exception e) {
            System.out.println("Error view compras: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTrirthQueryActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        model.setColumnCount(0);
        model.setRowCount(0);
        tblResult.setModel(model);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGIU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGIU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGIU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGIU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewGIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstQuery;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSecondQuery;
    private javax.swing.JButton btnTrirthQuery;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables
}
